const String SCAN_FAILED = "SCAN_FAILED";
const String BLUETOOTH_OFF = "BLUETOOTH_OFF";
const String PERMISSION_DENIED = "PERMISSION_DENIED";
const String NOT_SUPPORTED = "NOT_SUPPORTED";
const String DATABASE_FAILURE = "DATABASE_FAILURE";
